### ISSUE TITLE
I'd love to see some examples :)

### ISSUE THREAD

**Issue by ccorcos** [mapbox/cloudfriend#26]

**Comment by NOtherDev** [comment]
You might also have a look at a bit different alternative that is using TypeScript for strongly-typed resource types: [cloudform](https://www.npmjs.com/package/cloudform).

*Note*: this is a shameless plug, I'm the author of cloudform.

**Comment by rclark** [comment]
Hi! Sorry there aren't any examples in this repository, but here are some templates you can have a look at that illustrate how we actively use the library at Mapbox (alongside some other tools like https://github.com/mapbox/ecs-watchbot and https://github.com/mapbox/hookshot)!

https://github.com/mapbox/stork/blob/master/cloudformation/stork.template.js
https://github.com/mapbox/ecs-conex/blob/master/cloudformation/ecs-conex.template.js
https://github.com/mapbox/ecs-telephone/blob/master/cloudformation/ecs-telephone.template.js

Note that cloudfriend is a very very gentle helper for writing CloudFormation in JS -- it doesn't aim to recreate the template-authoring experience or provide a native JS object model. It just makes cloudformation intrinsic functions look like JS functions:

```js
cf.join('-', ['mapbox', cf.accountId, cf.region])
```

... instead of ...

```js
{ 'Fn::Join': ['-', ['mapbox', 'AWS::AcountId', 'AWS::Region']] }
```
