### ISSUE TITLE
alternative installation instructions in readme

### ISSUE THREAD

**Issue by s-heisler** [mapbox/cloudfriend#28]
Neither of the methods for installing that are currently listed in the Readme worked for me, but the following did the trick:
```npm install @mapbox/cloudfriend --save-dev```

Propose adding it to the Readme docs.

**Comment by rclark** [comment]
The instructions in the readme are about making a global install of cloudfriend, so that you can use the commands `build-template` and `validate-template` in your shell.

You were trying to install cloudfriend as a module dependency to another project. I'm not sure if we really need to document that since that's really just a part of using npm. But by that same logic, there's no real need to document a global install!

I'm going to close the issue here, but I'd be happy to merge a PR if you'd like to add some clarity to the readme!
