### ISSUE TITLE
[proposal] Shortcuts for Glue resources

### ISSUE THREAD

**Issue by rclark** [mapbox/cloudfriend#73]
The Glue resources have a lot of properties with pretty poor documentation on what values are allowed, what properties are required, or what those properties are even used for. Often I've had to figure out what I want my CloudFormation to look like by first creating the thing I want via API call or the console, then asking the API to give me the resource description and translating that into CloudFormation.

By making shortcuts, we might be able to short-circuit some of that nonsense and make it easier to manage databases and tables in CloudFormation.

Proposed shortcuts:

- **GlueDatabase**: A name is all that's required.
- **OrcGlueTable**: Define a table sourced from ORC files on S3. Name, Location, Columns are required.
- **JsonGlueTable**: Define a table sourced from line-delimited JSON files on S3. Name, Location, Columns are required.
- **GlueView**: Define a view by providing a name and some SQL (I'm still proving out that this works in CloudFormation).

Curious to hear thoughts and suggestions @Ramshackle-Jamathon @drboyer @danmactough

**Comment by danmactough** [comment]
I think these are great things to make simpler with shortcuts.

I've done a first pass at some similar tooling (Mapbox-internal):
- [helper to transform a JSON schema into a Glue table definition](https://github.com/mapbox/geodata/blob/master/shared/lib/json-schema.js)
- [helper to build CloudFormation using ☝️ ](https://github.com/mapbox/geodata/blob/master/cloudformation/schemas/helpers.js)

Although some of that tooling is specific to going from JSON schema to Glue table, the overall goal is still shortcuts for building CloudFormation. (And FWIW, there are great benefits to defining your tables with JSON schema as the one source-of-truth. For example, we use the same JSON schema in our PySpark integration tests; meaning the tests' schemas never diverge from production.)

**Comment by drboyer** [comment]
I'd be onboard with abstracting away some of the complexities of creating Glue tables/etc. They do have a myriad of properties, many of which can be left alone, but why leave that confusion to all end users?

Is your proposal for the GlueTables where only a few properties are required that some additional properties could still be set optionally? One omission I see from your list, which may just be because it's not necessarily required by all table definitions, is `PartitionKeys`, which can be a list of [Columns](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-tables.html#aws-glue-api-catalog-tables-Column).

Since tables _are_ partitioned more often than not, it'd be wise to be sure that's supported.

**Comment by danmactough** [comment]
> One omission I see from your list, which may just be because it's not necessarily required by all table definitions, is `PartitionKeys`, which can be a list of [Columns](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-tables.html#aws-glue-api-catalog-tables-Column).

Same for `SortColumns`, but neither should be **required** IMO. (Although, I think `PartitionKeys` being optional -- yet potentially such a bad idea to omit -- raises an interesting question of how opinionated to be. For example, we _could_ make `PartitionKeys` required, so that you would need to explicitly pass an empty array `[]` to disable partitions. Personally, I would prefer it not be required.)

**Comment by Ramshackle-Jamathon** [comment]
🎉 this is great I think having some shortcuts will improve the existing cloudformation glue abstraction's broad scope and lack of documentation.

I can also imagine that from the mapbox org perspective we might want to provide some defaults that wouldn't belong in a public library. Thinking of `location` in particular. Would it be crazy to have cloudfriend include the unopinionated shortcuts that are then further extended in some other private cloudformation library?

**Comment by rclark** [comment]
The general pattern I try to go for when writing a shortcut is to allow _any cloudformation property_ to be changed, but to set default values for as many as possible. So that would probably mean a default of no `PartitionKeys` and no `SortColumns`, the caller would be able to set those properties for sure.

> Would it be crazy to have cloudfriend include the unopinionated shortcuts that are then further extended in some other private cloudformation library?

I don't think this is even a little bit crazy.
